language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=mysql
bundler_args: --without development
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rake spec
notifications:
  email: false
