sys:
  #暗号化パスワード
  crypt_pass: pass

  #承認者候補に他所属の管理者を表示
  recognizers_include_admin: false

  #自動リンクチェック
  auto_link_check: true

  # 書き出しファイル転送設定
  log_closed_page: false
  transfer_to_publish: false
  transfer_opts: "-rlptvz --delete"
  transfer_opt_exclude: "config/rsync/public_exclude.lst"
  transfer_opt_include: "config/rsync/public_include.lst"
  transfer_opt_remote_shell: "ssh -p 22"

cms:
  # プレビューURL（ドメイン）
  # 'site'(default) or 'core'
  preview_domain: "site"

  #ページ数付きページ書き出し数
  publish_more_pages: 10

  # Kana, Talk
  use_kana: true
  use_kana_exclude_site_ids:
#    - 1
#    - 2
#    - 3

  # Accessibility check setting
  enable_accessibility_check: true

  # Kana settings
  mecab_index: "/usr/local/libexec/mecab/mecab-dict-index"
  mecab_dic: "/usr/local/lib/mecab/dic/ipadic"

  # Talk settings
  sox_bin: "/usr/bin/sox"
  lame_bin: "/usr/local/bin/lame"
  talk_bin: "/usr/local/bin/open_jtalk"
  talk_dic: "/usr/local/share/open_jtalk/dic"
  talk_voice: "config/voices/mei_normal/mei_normal.htsvoice"
  talk_opts: "-s 48000 -p 300 -u 0.5 -jm 0.5 -jf 0.5"
  talk_strlen: 500

gp_article:
  #携帯用内容制限[Bytes]
  body_limit_for_mobile: 81920
