-
  name: "元日"
  date: "1月1日"
  description: "年のはじめを祝う"
  kind: "holiday"
-
  name: "成人の日"
  date: "1月の第2月曜日"
  description: "おとなになったことを自覚し、みずから生き抜こうとする青年を祝いはげます"
  kind: "holiday"
-
  name: "建国記念の日"
  date: "2月11日"
  description: "建国をしのび、国を愛する心を養う"
  kind: "holiday"
-
  name: "春分の日"
  date: "春分日"
  description: "自然をたたえ、生物をいつくしむ"
  kind: "holiday"
-
  name: "昭和の日"
  date: "4月29日"
  description: "激動の日々を経て、復興を遂げた昭和の時代を顧み、国の将来に思いをいたす"
  kind: "holiday"
-
  name: "憲法記念日"
  date: "5月3日"
  description: "日本国憲法の施行を記念し、国の成長を期する"
  kind: "holiday"
-
  name: "みどりの日"
  date: "5月4日"
  description: "自然に親しむとともにその恩恵に感謝し、豊かな心をはぐくむ"
  kind: "holiday"
-
  name: "こどもの日"
  date: "5月5日"
  description: "こどもの人格を重んじ、こどもの幸福をはかるとともに、母に感謝する"
  kind: "holiday"
-
  name: "海の日"
  date: "7月の第3月曜日"
  description: "海の恩恵に感謝するとともに、海洋国日本の繁栄を願う"
  kind: "holiday"
-
  name: "敬老の日"
  date: "9月の第3月曜日"
  description: "多年にわたり社会につくしてきた老人を敬愛し、長寿を祝う"
  kind: "holiday"
-
  name: "秋分の日"
  date: "秋分日"
  description: "祖先をうやまい、なくなった人々をしのぶ"
  kind: "holiday"
-
  name: "体育の日"
  date: "10月の第2月曜日"
  description: "スポーツにしたしみ、健康な心身をつちかう"
  kind: "holiday"
-
  name: "文化の日"
  date: "11月3日"
  description: "自由と平和を愛し、文化をすすめる"
  kind: "holiday"
-
  name: "勤労感謝の日"
  date: "11月23日"
  description: "勤労をたっとび、生産を祝い、国民たがいに感謝しあう"
  kind: "holiday"
-
  name: "天皇誕生日"
  date: "12月23日"
  description: "天皇の誕生日を祝う"
  kind: "holiday"
